### ISSUE TITLE
Nested CSS-in-JS

### ISSUE THREAD

**Issue by JadeMaveric** [engicos/companion#2]
Next.js doesn't support nested classes in CSS-in-JS. To fix this, I had to restructure most of it. The downside is that the naming becomes redundant and messy. We might have to look to an alternative to CSS-in-JS. #1

**Comment by vipulchodankar** [comment]
Actually, i had enabled SASS support.

See here for example:
https://github.com/engicos/companion/blob/master/components/courses/ContactCard.js

**Comment by vipulchodankar** [comment]
I would suggest any of the following options:
- Stick to the current method
- Use Styled components
- Use CSS modules with Sass - requires css files

All the options are scoped and are quite easy to use.

**Comment by JadeMaveric** [comment]
I like the idea of using css files. Separate the logic from the styling.

**Comment by JadeMaveric** [comment]
This will be fixed as part of #1
